routes/web.php
<?php

use App\Http\Controllers\AccountController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\FollowController;
use App\Http\Controllers\NotificationsController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PostController;
use App\Models\User;

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    $users = User::withTrashed()->get();

    $currentUser = Auth::user();
//    return $currentUser;
    $notificationCount = Auth::user()->unreadNotifications()->count();
    return view('dashboard', [
        'currentUser' => $currentUser,
        'users' => $users,
        'notificationCount' => $notificationCount
    ]);
})->middleware(['auth'])->name('dashboard');


Route::group([ 'prefix' => '/posts', 'middleware' => 'auth' ], function() {
    Route::get('/', [PostController::class, 'index'])->name('posts.index');
    Route::get('/create', [PostController::class, 'create'])->name('posts.create');
    Route::post('/', [PostController::class, 'store'])->name('posts.store');

    Route::group(['prefix' => '/{post}'], function() {
        Route::get('/', [PostController::class, 'view'])->name('posts.view')->middleware('age');
        Route::delete('/', [PostController::class, 'delete'])->name('posts.delete');
    });

    Route::post('/comment/store', [CommentController::class,'store'])->name('comment.add');

    Route::group(['prefix' => 'reply'], function() {
        Route::post('/', [CommentController::class,'replyStore'])->name('reply.add');
        Route::put('/{id}', [CommentController::class,'replyEdit'])->name('reply.edit');
        Route::delete('/{id}', [CommentController::class,'replyDelete'])->name('reply.delete');
    });
});


Route::group([ 'prefix' => '/account', 'middleware' => 'auth' ], function() {
    Route::get('/', [AccountController::class, 'index'])->name('account.index');
    Route::get('/edit', [AccountController::class, 'edit'])->name('account.edit');
    Route::put('/', [AccountController::class, 'update'])->name('account.update');
    Route::get('/changepassword', [AccountController::class, 'changePassword'])->name('account.changepassword');
    Route::post('/changepassword', [AccountController::class, 'storeChangePassword'])->name('account.storechangepassword');
    Route::get('/deleteprofilepic', [AccountController::class, 'deleteProfilePic'])->name('account.deleteprofilepic');
});

Route::group(['prefix' => '/notifications', 'middleware' => 'auth' ], function() {
    Route::get('/', [NotificationsController::class, 'index'])->name('notifications');
    Route::get('/markasreadall', [NotificationsController::class, 'markAsReadAll'])->name('notifications.markasreadall');
    Route::get('/delete', [NotificationsController::class, 'delete'])->name('notifications.delete');
    Route::get('/markasread/{id}', [NotificationsController::class, 'markAsReadOne'])->name('notifications.markasread');
});

Route::get('/follow/{user_id}', [FollowController::class, 'follow'])->name('follow');
Route::get('/unfollow/{user_id}', [FollowController::class, 'unfollow'])->name('unfollow');

require __DIR__.'/auth.php';

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/dashboard.blade.php
<style>
    .card {
        width: 375px;
        margin: 10px;
        box-shadow: 1px 1px 5px grey;
        padding: 1.5rem;
        border-radius: 0.5rem;
    }
    .card.deleted {
        opacity: 0.5;
    }
</style>

<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-right text-xl text-gray-800 leading-tight">
            <x-nav-link :href="route('notifications')" :active="request()->routeIs('notifications')">
                {{ __('Notifications') }}
                <h1 class="text-red-900 font-bold p-1 ml-2">{{$notificationCount}}</h1>
            </x-nav-link>
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div  class="bg-white pb-3 overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-gray-400 border-b border-gray-200">
                    <h1>Welcome {{ $currentUser->name }} !!</h1>
                </div>

                <h1 style="font-size: 20px;" class=" py-5 text-center uppercase">All Users</h1>
                <div class="p-3 flex flex-wrap">
                    @foreach($users as $user)
                        @if($user == $currentUser)
                            <div class="card bg-gray-200">
                                <h1>Name: {{ $user->name }} (You)</h1>
                                <h1>Email: {{ $user->email }} </h1>
                                <h1>Username: {{ $user->username }} </h1>
                                <h1>Phone no: {{ $user->phone }} </h1>
                                <h1>Birth Date: {{ $user->date_of_birth }} </h1>
                                <h1>Last login: {{ $user->last_login }} </h1>
                                <div>
                                    <h1 class="">Languages Known: </h1>
                                    @foreach($user->languages_known as $language)
                                        <span style="color: #8d1414"> {{ $language }}, </span>
                                    @endforeach
                                </div>
{{--                                <a href="" class="ac-button">Delete User</a>--}}
                            </div>
                        @elseif($user->deleted_at != '')
                            <div class="card deleted">
                                <h1>Name: {{ $user->name }} </h1>
                                <h1>Email: {{ $user->email }} </h1>
                                <h1>Username: {{ $user->username }} </h1>
                                <h1>Phone no: {{ $user->phone }} </h1>
                                <h1>Birth Date: {{ $user->date_of_birth }} </h1>
                                <h1>Last login: {{ $user->last_login }} </h1>
                                <div>
                                    <h1 class="">Languages Known: </h1>
                                    @foreach($user->languages_known as $language)
                                        <span style="color: #8d1414"> {{ $language }}, </span>
                                    @endforeach
                                </div>
{{--                                <a href=""  class="ac-button">Delete User</a>--}}
                            </div>
                        @else
                            <div class="card bg-gray-50">
                                <h1>Name: {{ $user->name }} </h1>
                                <h1>Email: {{ $user->email }} </h1>
                                <h1>Username: {{ $user->username }} </h1>
                                <h1>Phone no: {{ $user->phone }} </h1>
                                <h1>Birth Date: {{ $user->date_of_birth }} </h1>
                                <h1>Last login: {{ $user->last_login }} </h1>
                                <div>
                                    <h1 class="">Languages Known: </h1>
                                    @foreach($user->languages_known as $language)
                                        <span style="color: #8d1414"> {{ $language }}, </span>
                                    @endforeach
                                </div>
                                {{--                                <a href=""  class="ac-button">Delete User</a>--}}
                            </div>
                        @endif
                    @endforeach
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/notifications.blade.php
<style>
    .card {
        margin: 10px;
        box-shadow: 1px 1px 5px grey;
        padding: 1.5rem;
        border-radius: 0.5rem;
    }
    .btn {
        display: block;
        color: white;
        padding: 10px 16px;
        border-radius: 5px;
        width: 130px;
        box-sizing: border-box;
        margin-top: 10px;
        cursor: pointer;
        text-align: center;
    }

    .btn.btn-reply {
        background: rgba(77, 79, 88, 0.76);
    }

</style>

<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-right text-xl text-gray-800 leading-tight">
            <x-nav-link :href="route('notifications')" :active="request()->routeIs('notifications')">
                {{ __('Notifications') }}
                <h1 class="text-red-900 font-bold p-1 ml-2">{{$notificationCount}}</h1>
            </x-nav-link>
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div  class="bg-white pb-3 overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-gray-400 border-b border-gray-200">
                    <h1>Welcome {{ $username }} !!</h1>
                </div>
                <h1 style="font-size: 20px;" class=" py-5 text-center uppercase">All Users</h1>
                <div class="p-3 card">
                    <div class="flex justify-between bg-red-100 p-3 m-4" style="align-items: center">
                        <h1 class="text-red-900 font-bold ">Unread Notifications</h1>
                        <a class="bg-red-900 text-white py-2 px-4 rounded" href={{ route('notifications.markasreadall') }} >Read All</a>
                    </div>
                    @foreach($unreadNotifications as $notification)
                        @if($notification->type == 'App\Notifications\CommentCreateNotification')
                        <div class="notification-card shadow-sm rounded p-3 m-4 bg-gray-200">
                            <h1 class="font-bold my-2">{{$username}}</h1>
                            <h1 class="my-2">{{$notification->data['username']}} Has Comment on Your Post</h1>
                            <h1>Title: {{$notification->data['title']}}</h1>
                            <div class="flex">
                                <a class="btn btn-reply" href={{ route('posts.view', ['post' => $notification->data['id']]) }}>Show Post</a>
                                <a class="btn-reply ml-3 btn" href={{ route('notifications.markasread', ['id' => $notification->id]) }} >Read</a>
                            </div>
                        </div>
                        @else
                            <div class="notification-card shadow-sm rounded p-3 m-4 bg-gray-200">
                                <h1 class="font-bold my-2">{{$username}}</h1>
                                <h1 class="my-2">{{$notification->data['username']}} Has Reply on Your Comment</h1>
                                <h1>Title: {{$notification->data['body']}}</h1>
                                <div class="flex">
                                    <a class="btn btn-reply" href={{ route('posts.view', ['post' => $notification->data['id']]) }}>View Post</a>
                                    <a class="btn-reply ml-3 btn" href={{ route('notifications.markasread', ['id' => $notification->id]) }} >Read</a>
                                </div>
                            </div>
                        @endif
                    @endforeach
                    <div class="flex justify-between bg-green-100 p-3 m-4" style="align-items: center">
                        <h1 class="text-green-900 font-bold ">Readed Notifications</h1>
                        <a class="bg-green-900 text-white py-2 px-4 rounded" href={{ route('notifications.delete') }} >Delete</a>
                    </div>
                    @foreach($readNotifications as $notification)
                        @if($notification->type == 'App\Notifications\CommentCreateNotification')
                        <div class="notification-card shadow-sm rounded p-3 m-4 bg-gray-200">
                            <h1 class="font-bold my-2">{{$username}}</h1>
                            <h1 class="my-2">{{$notification->data['username']}} Has Comment on Your Post</h1>
                            <h1>Title: {{$notification->data['title']}}</h1>
                            <a class="btn btn-reply" href={{ route('posts.view', ['post' => $notification->data['id']]) }}>Show Post</a>
                        </div>
                        @else
                            <div class="notification-card shadow-sm rounded p-3 m-4 bg-gray-200">
                                <h1 class="font-bold my-2">{{$username}}</h1>
                                <h1 class="my-2">{{$notification->data['username']}} Has Reply on Your Comment</h1>
                                <h1>Title: {{$notification->data['body']}}</h1>
                                <a class="btn btn-reply" href={{ route('posts.view', ['post' => $notification->data['id']]) }}>Show Post</a>
                            </div>
                        @endif
                    @endforeach
                </div>
            </div>
        </div>
    </div>
</x-app-layout>